version: "3.9"
services:
  storefront:
    build:
      context: ./storefront
      args:
        # Передаємо змінну на етап збирання Dockerfile
        REACT_APP_API_URL: ${BACKEND_URL}
    container_name: storefront
    restart: always
    networks:
      - appnet


  admin:
    build:
      context: ./admin-panel
      args:
        # Передаємо змінну на етап збирання Dockerfile
        VITE_API_URL: ${BACKEND_URL}
    container_name: admin
    restart: always
    networks:
      - appnet

  backend:
    build: ./nest-backend
    container_name: backend
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRESS_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRESS_PASSWORD: ${POSTGRES_PASSWORD}
      PRIVATE_KEY: ${PRIVATE_KEY}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
      CORS_RULE: ${CORS_RULE}

    networks:
      - appnet
    depends_on:
      - db
    command: >
      sh -c "
        npm run seed &&
        npm run start:prod
      "
    volumes:
      - static_data:/app/static
  
  nginx:
    image: nginx:stable
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx-proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - storefront
      - admin
      - backend
    networks:
      - appnet

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet

networks:
  appnet:

volumes:
  postgres_data:
  static_data:
    driver: local
